[project]
name = "fbrefstats"
version = "0.1.12"
authors = [
  { name="Mohamed Brahimi"},
]
description = "A Python script to scrape football data from FBRef"
readme = "README.md"
requires-python = ">=3.5"
license = { file = "LICENSE.txt" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
    "Operating System :: OS Independent",
]
keywords = ["soccer", "football", "scraping", "webscraping", "FBRef"]
dependencies = ["requests", "pandas", "bs4", "fake_http_header"]

[project.urls]
Homepage = "https://github.com/mbrahimi25/fbrefstats"
Documentation = "https://github.com/mbrahimi25/fbrefstats/blob/main/DOCUMENTATION.md"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"