[package]
name = "puzzle-party"
version = "0.1.0"
edition = "2021"

[lib]
name = "puzzle_party"
crate-type = ["cdylib"]

[dependencies]
rand = "0.8.5"

[dependencies.pyo3]
version = "0.23.1"
features = ["abi3-py38"]
