[tool.poetry]
name = "interactive-process"
version = "0.1.0"
description = ""
authors = ["Yason Khaburzaniya <yason@hey.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
pytest = "^8.3.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
