[tool.poetry]
name = "commitcrafter"
version = "0.3.1"
description = "A CLI tool to generate commit messages based on git diffs using AI"
authors = ["mpruvot <marius.pruvot@outlook.fr>"]
readme = "README.md"

[tool.poetry.scripts]
commitcraft = "commitcrafter.cli:app"

[tool.poetry.dependencies]
python = "^3.12"
pytest = "^8.1.1"
typer = "0.12.3"
ruff = "^0.9.2"
gitpython = "^3.1.43"
openai = "^1.23.1"
rich = "^13.7.1"
pyperclip = "^1.9.0"
pydantic-ai = "^0.0.19"
mypy = "^1.14.1"
pre-commit = "^4.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

