[tool.poetry]
name = "aws-ninja"
version = "0.2.0"
description = "A collection of tools to use when reviewing AWS accounts and their setup."
authors = ["Lawrence <lawrence@acode.ninja>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
boto3 = "^1.34.148"
jinja2 = "^3.1.4"
cement = "^3.0.10"
click = "^8.1.7"
jsonpickle = "^3.2.2"

[tool.poetry.scripts]
aws-ninja = "aws_ninja.cli:aws_ninja"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
