[tool.poetry]
authors = ["Daniel CAUNE <daniel.caune@gmail.com>"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: Other/Proprietary License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Topic :: Software Development :: Libraries",
]
description = "Python server framework for quickly building RESTful APIs with minimal effort"
include = [
    "CHANGELOG.md"
]
keywords = ["perseus", "resful", "api", "server", "framework"]
license = "Proprietary"
name = "perseus-restful-api-framework"
packages = [{ include = "majormode", from = "src" }]
readme = "README.md"
repository = "https://github.com/majormode/perseus-restful-api-server-framework"
version = "1.28.15"

[tool.poetry.dependencies]
pillow = "^10.4.0"
perseus-core-library = "^1.20.5"
perseus-getenv-library = "^1.0.5"
perseus-microrm-library = "^1.3.9"
pymemcache = "^4.0.0"
prosoponym = "^1.2.4"
psutil = "^5.9"
python = ">=3.10"
setuptools = "^75.1.0"
tornado = "^6.4.1"

[tool.poetry.dev-dependencies]
fabric = "^3.0.0"
sphinx = "^8.0.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
