[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "snapmanager"
version = "0.1.8"
description = "Makes VSS snapshot disks bootable in Google Cloud"
readme = "README.md"
authors = [{name = "Ali Aktas"}]
license = {text = "MIT"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: System :: Systems Administration",
]
requires-python = ">=3.8"
dependencies = [
    "google-cloud-compute>=1.23.0",
    "rich>=10.0.0",
    "pywinrm>=0.4.3",
    "click>=8.0.0"
]

[project.scripts]
snapmanager = "snapmanager.cli:main"

[project.urls]
repository = "https://github.com/aliaktas/snapmanager"
