[project]
name = "fspacker"
dynamic = ["version"]

[tool.poetry]
name = "fspacker"
version = "0.6.3"
description = "Fast & Simple Packer toolset for python."
authors = ["gooker_young <gooker_young@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.1.8"
pkginfo = "^1.12.0"
stdlib-list = "~0.10"
requests = "^2.32.3"
types-requests = "^2.32.0.20241016"

[[tool.poetry.source]]
name = "aliyun"
url = "http://mirrors.aliyun.com/pypi/simple/"
priority = "primary"

[tool.poetry.scripts]
fsp = "fspacker.cli:main"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
tox = "^4.23.2"
coverage = "~7.5"
pytest-benchmark = "~4"
pytest-html = "~4.1"
pytest-cov = "~4"
mypy = "^1.14.1"
black = "~24"

[tool.poetry.group.docs.dependencies]
sphinx = "~7"
sphinx-autodoc-typehints = "~2"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "pep440"

[tool.poetry-dynamic-versioning.files."fspacker/__init__.py"]
persistent-substitution = true
initial-content = """
# These version placeholders will be replaced later during substitution.
__version__ = "0.0.0"
__version_tuple__ = (0, 0, 0)
"""

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"
