[default]
service_name = "xhm sdk"
log_level = "DEBUG"
# CACHE_MODE = ""，则不开启redis配置
# CACHE_MODE = ”all", 全部key走redis
# CACHE_MODE = "preferred"， 优选模式，选择部分key走redis
CACHE_MODE = ""
DB_HOST = "localhost"
DB_USER = "user"
DB_PASS = "pass"

[default.xhm_config_redis]
host = "localhost"
port = 6379
db = 0
password = ""

[default.llm]
openai_api_key = ""
openai_base_url = ""
openai_model = "gpt-4o"

[default.milvus]
URI = "http://xxx:19530"
HOST = "xxx"
PORT = 19530
TOKEN = ""
COLLECTION_NAME = "keywords_openai"


[default.xhm_smtp]
# https://help.aliyun.com/document_detail/602183.html?spm=a2c4g.11186623.0.0.15aa75d1y7FITs
host = "smtp.qiye.aliyun.com"
port = 465
sender_address = "noreply@askkf.com"
sender_password = "ZHG1ooooof~"
ssl = true

[production]
CACHE_MODE = ""
DB_HOST = "prod.db.server"
DB_USER = "prod_user"
DB_PASS = "prod_pass"