[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "swine"
version = "0.1.4"
authors = [
    { name = "Erik Dunteman", email = "erik@pig.dev" },
]
description = "Swine"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "requests>=2.0.0",
    "click>=8.0.0",
    "tabulate>=0.9.0",
    "iso8601>=1.0.0",
]

[project.scripts]
swine = "swine.cli:main"

[tool.hatch.build]
packages = ["src"]

[tool.hatch.build.targets.wheel]
packages = ["src/swine"] 