[build-system]
requires = ["setuptools>=63.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mistake-lang"
version = "0.1.7"
description = "A Mistake"
readme = "README.md"
authors = [
    {name = "Elliot", email = "captainexpo@gmail.com"}
]
license = {text = "MIT"}
requires-python = ">=3.7"

dependencies = [
    "annotated-types==0.7.0",
    "build==1.2.2.post1",
    "certifi==2024.12.14",
    "cffi==1.17.1",
    "charset-normalizer==3.4.1",
    "future==1.0.0",
    "gevent==24.11.1",
    "greenlet==3.1.1",
    "idna==3.10",
    "inflection==0.5.1",
    "pyairtable==3.0.1",
    "pyproject_hooks==1.2.0",
    "python-dotenv==1.0.1",
    "requests==2.32.3",
    "urllib3==2.3.0",
    "zope.event==5.0",
    "zope.interface==7.2"
]

[project.optional-dependencies]
vulkan = [
    "kp==0.9.0", 
    "vulkan", 
    "numpy==1.26.4"
]

[project.urls]
"Homepage" = "https://github.com/Captainexpo-1/Mistake-Lang"
"Source" = "https://github.com/Captainexpo-1/Mistake-Lang"
"Tracker" = "https://github.com/Captainexpo-1/Mistake-Lang/issues"

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
mistake-lang = "mistake.main:main"
