[project]
name = "good-utilities"
version = "0.1.37"
description = "Collection of utility functions"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []
[[project.authors]]
name = "SmartCookie"

[build-system]
requires = [ "poetry-core>=2.0.0,<3.0.0",]
build-backend = "poetry.core.masonry.api"
