[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ug_tagung"
version = "1.0.0"
description = "Adressverwaltung fÃ¼r Tagungen"
readme = "README.md"
licence = {file = "LICENSE"}
requires-python = ">=3.10"
dependencies = [
    "ugbib_divers",
    "ugbib_modell",
    "ugbib_tkinter",
    "ugbib_werkzeug",
    "Pillow",
    "psycopg2-binary",
    "PyYAML",
]
autors = [
    {name = "Ulrich Goebel", email = "ulrich@fam-goebel.de"},
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.hatch.build.targets.wheel]
packages = ["src/ug_tagung"]

[tool.setuptools]
packages = ["ug_tagung"]

[tool.setuptools.entry-points.console_scripts]
Tagung = "ug_tagung.Tagung:main"
