[package]
name = "uwu-python"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "uwu_python"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
uwuify = "^0.2"
rand = "0.8"
unidecode = "0.3.0"
