[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "bread_engine"
version = "0.1.1"
authors = [
  { name="maghje13", email="13maghje@gmail.com" },
]
description = "A python game engine using PyGame"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/maghje13/bread_engine"
PyPI = "https://pypi.org/project/bread-engine"