[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "drugname_standardizer"
version = "1.1.2"
description = "A Python tool for standardizing drug names using the latest FDA's UNII Names list."
readme = "README.md"
authors = [
    {name = "StÃ©phanie Chevalier", email = "pro.stephaniechevalier@gmail.com"}
]
license = {text = "MIT"}
dependencies = [
    "pandas>=2.2,<3.0",
    "requests>=2.32,<3.0",
    "tqdm>=4.66,<5.0"
]
requires-python = ">=3.7"
keywords = ["drugs", "drug name synonyms", "standardization", "FDA", "UNII"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/StephanieChevalier/drugname_standardizer"

[tool.setuptools.packages.find]
where = ["drugname_standardizer"]
include = ["drugname_standardizer"]

[tool.setuptools.package-data]
"drugname_standardizer" = ["data/UNII_Names.txt"]

[project.scripts]
drugname_standardizer = "drugname_standardizer.standardizer:main"
