[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyEDAkit"
version = "0.1.4"
description = "A toolkit for exploratory data analysis in Python"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Alberto Biscalchin", email = "biscalchin.mau.se@gmail.com" },
    { name = "Marco Schivo", email = "marcoschivo1@gmail.com" }
]
keywords = ["data analysis", "EDA", "machine learning"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Information Analysis"
]
dependencies = [
    "numpy>=1.21.0",
    "scipy>=1.7.0",
    "matplotlib>=3.4.0",
    "scikit-learn>=0.24.0",
    "pandas>=1.3.0",
    "networkx>=2.5"
]
requires-python = ">=3.7"

[project.urls]
homepage = "https://github.com/zkivo/pyEDAkit"
repository = "https://github.com/zkivo/pyEDAkit"

[tool.setuptools.packages.find]
include = ["pyEDAkit*"]
exclude = ["datasets", "examples", "tests"]
