[project]
name = "ws-mcp"
version = "0.1.11"
description = "Wrap MCP servers with a WebSocket."
readme = "README.md"
authors = [{ name = "nick1udwig", email = "hosted-fornet@protonmail.com" }]
requires-python = ">=3.12"
dependencies = [
    "jsonschema>=4.23.0",
    "websockets>=14.1",
    "colorama>=0.4.6",
]

[project.urls]
GitHub = "https://github.com/nick1udwig/ws-mcp"

[project.scripts]
ws-mcp = "ws_mcp:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
