[tool.poetry]
name = "myprojectpythonReda"
version = "0.0.6"
description = "package for the python project 2025 class"
authors = ["Reda El Fassi"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pybacktestchain = "^0.2.1"


[tool.poetry.group.dev.dependencies]
python-semantic-release = "^9.16.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
[tool.semantic_release]
version_variable = "pyproject.toml:version"
version_toml = ["pyproject.toml:tool.poetry.version"]
branch = "master"

