[tool.poetry]
name = "camalis"
version = "2025.01.16"
description = ""
authors = ["RN Tecnologia <contato@rntecnologia.com.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.32.3"
python-dotenv = "^1.0.1"
pytest-mock = "^3.14.0"
pandas = "^2.2.2"
twine = "^6.0.1"


[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
isort = "^5.13.2"
black = "^24.4.0"
pytest-mock = "^3.14.0"
pandas = "^2.2.2"
matplotlib = "^3.8.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
