[project]
name = "lv-namedays"
version = "0.2.0"
description = "A CLI tool and a library for Latvian name day lookup"
readme = "README.md"
authors = [{name = "Uldis BojÄrs"}]
requires-python = ">=3.12"
keywords = ["Latvian", "name days", "nameday", "CLI"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = ["click"]

[project.optional-dependencies]
convert = ["pandas", "openpyxl"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

#[build-system]
#requires = ["setuptools"] 
#build-backend = "setuptools.build_meta"

[project.scripts]
nameday = "lv_namedays.nameday:main" 

[tool.setuptools.package-data]
lv_namedays = ["src/lv_namedays/data/*.json"]

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true


