[tool.poetry]
name = "structools"
version = "0.17.16"
description = ": Helpful tools for QIS and Pricing Structuring teams"
authors = ["Romain Pifaut"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
pandas = "^2.2.3"
plotly = "^5.24.1"
pydantic = "^2.10.5"
numpy = "1.26.0"
pybacktestchain = "^0.2.1"
streamlit = "^1.41.1"
pytest = "^8.3.4"
openpyxl = "^3.1.5"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
python-semantic-release = "^9.14.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
version_variable = "pyproject.toml:version"
version_toml = [
"pyproject.toml:tool.poetry.version",
]